### ISSUE TITLE
"oldDebeziumDbHistoryTopicName" in 0.20.0.M6 make cdc service startup with error

### ISSUE THREAD

**Issue by todli** [eventuate-tram/eventuate-tram-core#28]
I tried example TODO list (https://github.com/eventuate-tram/eventuate-tram-examples-java-spring-todo-list) 
with latest version of eventuate tram 0.20.0.M6, which is currently the master veresion of eventuate-tram-core
see the docker-compose yml attached:

_tramcdcservice:
  image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M6
  container_name: cdcservice
  restart: unless-stopped
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
    EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message_

When I start the eventuate containers, cdcservice throws an error that:

_cdcservice        | 
cdcservice        | Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
cdcservice        | 02:46:47.871 [main] ERROR o.s.boot.SpringApplication - Application startup failed
cdcservice        | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cdcPipelineConfigurator': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: oldDebeziumDbHistoryTopicName must not be blank (set 'none' to not migrate debezium offset storage data)
cdcservice        | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
cdcservice        | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
...
cdcservice        | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
cdcservice        | 	at io.eventuate.local.mysql.binlog.main.EventuateLocalCdcMysqlBinlogMain.main(EventuateLocalCdcMysqlBinlogMain.java:14)
cdcservice        | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
cdcservice        | Caused by: java.lang.IllegalArgumentException: oldDebeziumDbHistoryTopicName must not be blank (set 'none' to not migrate debezium offset storage data)
cdcservice        | 	at org.springframework.util.Assert.hasLength(Assert.java:157)
cdcservice        | 	at io.eventuate.local.unified.cdc.pipeline.dblog.mysqlbinlog.properties.MySqlBinlogCdcPipelineReaderProperties.validate(MySqlBinlogCdcPipelineReaderProperties.java:16)
cdcservice        | 	at io.eventuate.local.unified.cdc.pipeline.CdcPipelineConfigurator.createStartSaveCdcDefaultPipelineReader(CdcPipelineConfigurator.java:163)
cdcservice        | 	at io.eventuate.local.unified.cdc.pipeline.CdcPipelineConfigurator.lambda$initialize$0(CdcPipelineConfigurator.java:72)
cdcservice        | 	at java.util.Optional.orElseGet(Optional.java:267)
cdcservice        | 	at io.eventuate.local.unified.cdc.pipeline.CdcPipelineConfigurator.initialize(CdcPipelineConfigurator.java:71)
cdcservice        | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
cdcservice        | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
cdcservice        | 	... 26 common frames omitted_

The issues I have are:
- how to configure "oldDebeziumDbHistoryTopicName" to make cdcservice startup successfully without error
- I cannot find source codes of project "io.eventuate.local.unified" (https://mvnrepository.com/artifact/io.eventuate.local.java/eventuate-local-java-cdc-connector-unified/0.30.0.M7) on github for a reference, where can I get to the source page of this project?

any suggestion would be appreciated, thanks in advanced.

**Comment by cer** [comment]
The documentation for the new features of the CDC is forthcoming. 
This commit illustrates how to upgrade from the old CDC: https://github.com/microservices-patterns/ftgo-application/pull/19
You can also specify a value of none for that property.

In the meantime, please use a .RELEASE version.
